categories:
  demos:
    - video_id: "Eu5mYMavctM"
    - video_id: "LTYMWadOW7c"
    - video_id: "p3uBMqCPSDk"
    - video_id: "cpraXaw7dyc"
    - video_id: "Z3yQHYNXPws"
  
  news_coverage:
    - video_id: "s8hABHmA_NE"
    - video_id: "4ZP943-gARQ"
    - video_id: "IJQYW4a3rsM"
    - video_id: "ov4kk20ZUvo"
    - video_id: "b_SNExtznd4"
    - video_id: "O5--ZJwX6bI"
  
  reviews:
    - video_id: "j31dmodZ-5c"
    - video_id: "f3c4mQty_so"
    - video_id: "RPPMT9pVsO4"
    - video_id: "q2czJLPJ4nA"
    - video_id: "nmEy1_75qHk"